wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.16.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711598741.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
